In [18]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[3, 0],
              [1, 2]])

C = np.array([[1, 2, 3],
              [4, 5, 6]])

print("A:\n", A)
print("\nB:\n", B)
print("\nC:\n", C)

A:
 [[1 2]
 [3 4]]

B:
 [[3 0]
 [1 2]]

C:
 [[1 2 3]
 [4 5 6]]


In [19]:
# Verify shapes

print("A.shape:", A.shape)
print("B.shape:", B.shape)
print("C.shape:", C.shape) 

A.shape: (2, 2)
B.shape: (2, 2)
C.shape: (2, 3)


In [20]:
print("A + B :\n", A+B)


# Matrix A and C cannot be added as these are of different shapes
try:
    print("A + C :\n", A+C)
except ValueError as e:
    print("Error : ",e)

A + B :
 [[4 2]
 [4 6]]
Error :  operands could not be broadcast together with shapes (2,2) (2,3) 


In [21]:
print("A transpose:\n", np.transpose(A))

print("\nB transpose:\n", np.transpose(B))

print("\nC transpose:\n", np.transpose(C))

A transpose:
 [[1 3]
 [2 4]]

B transpose:
 [[3 1]
 [0 2]]

C transpose:
 [[1 4]
 [2 5]
 [3 6]]


In [22]:
left_side  = (A + B).T
right_side = A.T + B.T

print("(A + B).T:\n", left_side)
print("\nA.T + B.T:\n", right_side)
print("\nEqual?", np.array_equal(left_side, right_side))

(A + B).T:
 [[4 4]
 [2 6]]

A.T + B.T:
 [[4 4]
 [2 6]]

Equal? True


In [23]:
# Property 1: transposing twice gets you back to A
print("A:\n", A)
print("\n(A.T).T:\n", A.T.T)
print("Equal to A?", np.array_equal(A, A.T.T))

# Property 2: transpose of scalar multiple = scalar times transpose
left  = (3 * A).T
right = 3 * A.T
print("\n(3A).T equals 3*(A.T)?", np.array_equal(left, right))

A:
 [[1 2]
 [3 4]]

(A.T).T:
 [[1 2]
 [3 4]]
Equal to A? True

(3A).T equals 3*(A.T)? True
