In [1]:
import numpy as np


In [13]:
# Solving a 2X2 system

# 2x + 3y = 7
# 4x - y = 1

A = np.array([[2, 3],
              [4, -1]])
b = np.array([7, 1])

# Non zero determinant and Full rank so it should have unique solutions
print("Non-zero determinant of A ",np.linalg.det(A))
print("Rank of matrix A ",np.linalg.matrix_rank(A))

# np.linalg.solve does Gaussian elimination under the hood
x = np.linalg.solve(A, b)
print("Solution:", x)
print(f"x = {x[0]:.4f}, y = {x[1]:.4f}")

# Compare with your paper answer: x = 5/7 ≈ 0.7143, y = 13/7 ≈ 1.8571
print("\nExpected: x ≈ 0.7143, y ≈ 1.8571")


# Now Verify the x vector

# A @ x should equal b
print("Match?", np.allclose(A @ x, b))

Non-zero determinant of A  -14.000000000000004
Rank of matrix A  2
Solution: [0.71428571 1.85714286]
x = 0.7143, y = 1.8571

Expected: x ≈ 0.7143, y ≈ 1.8571
Match? True


In [15]:
# Solving a 3X3 system

# x + 2y + z = 6
# 2x + 5y + 3z = 16
# x + 4y + 2z = 13

A = np.array([[1, 2, 1],
              [2, 5, 3],
              [1, 4, 2]])
b = np.array([6, 16, 13])

# Non zero determinant and Full rank so it should have unique solutions
print("Non-zero determinant of A ",np.linalg.det(A))
print("Rank of matrix A ",np.linalg.matrix_rank(A))

x = np.linalg.solve(A, b)
print(f"Solution: x = {x[0]}, y = {x[1]}, z = {x[2]}")
# Expected: x = -1, y = 3, z = 1

# Verify
print("\nA @ x:", A @ x)
print("b    :", b)
print("Match?", np.allclose(A @ x, b))

Non-zero determinant of A  -1.0
Rank of matrix A  3
Solution: x = -1.0, y = 2.999999999999999, z = 1.0000000000000016

A @ x: [ 6. 16. 13.]
b    : [ 6 16 13]
Match? True


In [16]:
# In case of no solution or infinite solutions
# x + y = 3
# 2x + 2y = 10

A = np.array([[1, 1],
              [2, 2]])
b = np.array([3, 10])

# Check the determinant first
print(f"det(A) = {np.linalg.det(A):.4f}")
print(f"Rank of A = {np.linalg.matrix_rank(A)}")

# Try to solve — np.linalg.solve will fail
# np.linalg.solve here the guassian elemination method is not 
#  able to distinguish between no solution or infinitely many solutions
try:
    x = np.linalg.solve(A, b)
    print("Solution:", x)
except np.linalg.LinAlgError as e:
    print(f"Error: {e}")

det(A) = 0.0000
Rank of A = 1
Error: Singular matrix


In [21]:
# To distinguish between two singular matrix version : No solution and infinite solution
# We comapre the rank of matrix A with Augmented matrix

def diagnose_system(A, b):
    rank_A = np.linalg.matrix_rank(A)
    augmented = np.column_stack([A, b])
    rank_aug = np.linalg.matrix_rank(augmented)
    n = A.shape[1]   # number of unknowns
    
    print(f"  rank(A)        = {rank_A}")
    print(f"  rank([A|b])    = {rank_aug}")
    print(f"  num unknowns   = {n}")
    
    if rank_A < rank_aug:
        print("  → NO SOLUTION (system is inconsistent)")
    elif rank_A == rank_aug == n:
        print("  → UNIQUE SOLUTION")
    elif rank_A == rank_aug < n:
        print(f"  → INFINITELY MANY SOLUTIONS ({n - rank_A} free parameter(s))")

# Try it on all three Task systems
print("Task 1 (unique):")
diagnose_system(np.array([[2, 3], [4, -1]]), np.array([7, 1]))

print("\nTask 3 (no solution):")
diagnose_system(np.array([[1, 1], [2, 2]]), np.array([3, 10]))

print("\nTask 4 (infinite):")
diagnose_system(np.array([[1, 1], [2, 2]]), np.array([3, 6]))

Task 1 (unique):
[[ 2  3]
 [ 4 -1]]
[[ 2  3  7]
 [ 4 -1  1]]
(2, 2)
2
  rank(A)        = 2
  rank([A|b])    = 2
  num unknowns   = 2
  → UNIQUE SOLUTION

Task 3 (no solution):
[[1 1]
 [2 2]]
[[ 1  1  3]
 [ 2  2 10]]
(2, 2)
2
  rank(A)        = 1
  rank([A|b])    = 2
  num unknowns   = 2
  → NO SOLUTION (system is inconsistent)

Task 4 (infinite):
[[1 1]
 [2 2]]
[[1 1 3]
 [2 2 6]]
(2, 2)
2
  rank(A)        = 1
  rank([A|b])    = 1
  num unknowns   = 2
  → INFINITELY MANY SOLUTIONS (1 free parameter(s))


In [22]:
# Another way to solve for Ax = b is using A⁻¹ i.e A.A⁻¹ x = A⁻¹ .b  which is x = A⁻¹.b
# However using solve over the inverse method is faster and numerically stable.

import time

# A medium-sized invertible system
np.random.seed(0)
N = 500
A = np.random.rand(N, N)
b = np.random.rand(N)

# Method 1: inverse then multiply
start = time.time()
x1 = np.linalg.inv(A) @ b
t_inv = time.time() - start

# Method 2: solve directly
start = time.time()
x2 = np.linalg.solve(A, b)
t_solve = time.time() - start

print(f"Time with inverse: {t_inv*1000:.2f} ms")
print(f"Time with solve:   {t_solve*1000:.2f} ms")
print(f"Same answer?       {np.allclose(x1, x2)}")

SyntaxError: invalid character '⁻' (U+207B) (405586816.py, line 1)