In [16]:
import numpy as np


# Computing Svd of a matrix

A = np.array([[3, 0],
              [4, 5]])

U, singular_matrix, V_t = np.linalg.svd(A)

# verify svd computation

mid_result =  np.diag(singular_matrix) @ V_t
result = U @ mid_result


print("Is matrix A reconstructed through its svd ?",np.allclose(result,A))

# Now let us verify whether U and V are orthogonal

U_t = U.T
print("Is U orthogonal?", np.allclose(U.T @ U, np.eye(U.shape[0])))

V = V_t.T
print("Is V orthogonal?", np.allclose(V @ V_t, np.eye(V.shape[0])))

Is matrix A reconstructed through its svd ? True
Is U orthogonal? True
Is V orthogonal? True


In [22]:
# One of SVDs biggest won over eigen decomposition that it works on non-square, non-symmteric, 
# wide, tall , degenrate all size and type of matrices

A_wide = np.array([[1, 2, 3],
                   [4, 5, 6]])


U, singular_values, Vt = np.linalg.svd(A_wide)

# Here U is a sqaure matrix of size mXm and Vt is a sqaure amtrix of size nXn
# and singular_values is a array of singular values

print("U is \n",U)
print("\nVt is \n",Vt)
print("\nsingular_values is \n",singular_values)


# Build Σ with the correct shape (same as A)
Sigma = np.zeros(A_wide.shape)              # shape (2, 3)
Sigma[:len(singular_values), :len(singular_values)] = np.diag(singular_values)

print("\n Σ:\n", Sigma)


# Reconstruct
A_wide_reconstructed = U @ Sigma @ Vt
print("\nMatches original?", np.allclose(A_wide, A_wide_reconstructed))

U is 
 [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]

Vt is 
 [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]

singular_values is 
 [9.508032   0.77286964]

 Σ:
 [[9.508032   0.         0.        ]
 [0.         0.77286964 0.        ]]

Matches original? True


In [24]:
# A tall matrix svd


A_tall = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

print("A_tall shape:", A_tall.shape)

U, singular_values, Vt = np.linalg.svd(A_tall)

Sigma = np.zeros(A_tall.shape)              # shape (2, 3)
Sigma[:len(singular_values), :len(singular_values)] = np.diag(singular_values)

A_tall_reconstructed = U @ Sigma @ Vt
print("\nMatches original?", np.allclose(A_tall, A_tall_reconstructed))


A_tall shape: (3, 2)

Matches original? True


In [26]:
# One of SVD's useful property is identifying rank via count of non-zero singular values 

A_full = np.array([[3, 0],
                   [4, 5]])

U, sv, Vt = np.linalg.svd(A_full)

print("Singular values:", sv)
print("Rank via SVD (count of non-zero singular values):", np.sum(sv > 1e-10))
print("Rank via np.linalg.matrix_rank:", np.linalg.matrix_rank(A_full))

Singular values: [6.70820393 2.23606798]
Rank via SVD (count of non-zero singular values): 2
Rank via np.linalg.matrix_rank: 2


In [27]:
# Now let us verify for a rank deficient matrix here the rank of the amtrix is one.

# Row 2 is exactly 2× row 1 → rank-deficient
A_singular = np.array([[1, 2],
                       [2, 4]])

U, sv, Vt = np.linalg.svd(A_singular)

print("Singular values:", sv)
print("Rank via SVD:", np.sum(sv > 1e-10))
print("Rank via matrix_rank:", np.linalg.matrix_rank(A_singular))
print("Determinant:", np.linalg.det(A_singular))

Singular values: [5.00000000e+00 1.81443681e-16]
Rank via SVD: 1
Rank via matrix_rank: 1
Determinant: 0.0


In [29]:
# Almost rank-deficient but not exactly
A_near_singular = np.array([[1.0, 2.0],
                            [2.001, 4.0]])  # row 2 is *almost* 2× row 1

U, sv, Vt = np.linalg.svd(A_near_singular)

print("Singular values:", sv)
print("Rank via SVD:", np.sum(sv > 1e-10))
print("Rank via matrix_rank:", np.linalg.matrix_rank(A_near_singular))

Singular values: [5.00040007e+00 3.99967997e-04]
Ratio σ₁/σ₂ (condition number): 12502.000420007304
Rank via SVD: 2
Rank via matrix_rank: 2
