In [12]:
import numpy as np



# Build a symmetric matrix and verify

A = np.array([[4, 2],
              [2, 1]])

print("\nIs A symmetric (A == A.T)?", np.array_equal(A, A.T))


Is A symmetric (A == A.T)? True


In [13]:
# Now verify wheter the egien vecotr matrix of a symmetrical matrix is orthogonal or not

# Find eigen vector and eigen values
eigenvalues, eigenvectors = np.linalg.eigh(A)

v1 = eigenvectors[:, 0]
v2 = eigenvectors[:, 1]

print("\n||v1|| =", np.linalg.norm(v1))      # should be 1
print("||v2|| =", np.linalg.norm(v2))        # should be 1
print("\nv1 · v2 =", np.dot(v1, v2))        # should be 0



||v1|| = 0.9999999999999999
||v2|| = 0.9999999999999999

v1 · v2 = 0.0


In [14]:
# Now also see for the other property of orthogonal matrix.
# Qᵀ @ Q = I

Q = eigenvectors

QtQ = Q.T @ Q
print("\nClose to identity?", np.allclose(QtQ, np.eye(2)))


Close to identity? True


In [15]:
# Now let us verify the spectral theorem
# A = Q · Λ · Qᵀ

Lambda = np.diag(eigenvalues)
A_reconstructed = Q @ Lambda @ Q.T

print("\nClose to A?", np.allclose(A, A_reconstructed))


Close to A? True


In [16]:
# A non symmetrical matrix does not gurantee orthogonal eigen vectors

# Yesterday's matrix (not symmetric)
B = np.array([[4, 1],
              [2, 3]])

print("B is symmetric?", np.array_equal(B, B.T))

eigenvalues_B, eigenvectors_B = np.linalg.eig(B)
v1_B = eigenvectors_B[:, 0]
v2_B = eigenvectors_B[:, 1]

print("\nEigenvectors of B:\n", eigenvectors_B)
print("\nDot product v1·v2 =", np.dot(v1_B, v2_B))

B is symmetric? False

Eigenvectors of B:
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]

Dot product v1·v2 = 0.3162277660168379


In [17]:
# Using a bigger amtrix structure to internalize the workflow
# Build a symmetric matrix from a random non-symmetric one using M + M.T
np.random.seed(42)
M = np.random.rand(5, 5)
S = M + M.T

print("S symmetric?", np.allclose(S, S.T))

# Decompose
eigenvalues, Q = np.linalg.eigh(S)
print("\nEigenvalues (sorted ascending):", eigenvalues)

# Verify orthogonality of Q
print("\nIs Q orthogonal (Qᵀ Q = I)?", np.allclose(Q.T @ Q, np.eye(5)))

# Verify reconstruction
S_reconstructed = Q @ np.diag(eigenvalues) @ Q.T
print("Reconstruction matches?", np.allclose(S, S_reconstructed))

S symmetric? True

Eigenvalues (sorted ascending): [-1.31408512 -0.02902499  0.19807806  0.92223505  4.52895975]

Is Q orthogonal (Qᵀ Q = I)? True
Reconstruction matches? True


In [22]:
import numpy as np

# Set NumPy print options to match the 6-decimal precision in your assignment
np.set_printoptions(precision=6, suppress=True)

def print_eigen_info(name, matrix):
    print(f"\n{'='*20}\n{name} Analysis\n{'='*20}")
    # Calculate eigenvalues and eigenvectors
    vals, vecs = np.linalg.eig(matrix)
    
    # Sort by absolute magnitude descending (Standard definition of "dominant")
    idx = np.argsort(np.abs(vals))[::-1]
    vals_sorted = vals[idx]
    vecs_sorted = vecs[:, idx]
    
    print("Eigenvalues (Sorted: 1st dominant -> least dominant):")
    print(vals_sorted)
    
    print("\nEigenvectors (Columns correspond to the sorted eigenvalues above):")
    print(vecs_sorted)

# --- E2: Least dominant eigenvalue ---
E2 = np.array([
    [-8, -5, -17,  7],
    [-5, 12,  15, 11],
    [-17, 15, -10,  9],
    [ 7, 11,   9, 16]
])
print_eigen_info("E2", E2)

# --- E3: Third dominant eigenvector ---
E3 = np.array([
    [-4,  7,  10,  -3],
    [ 7, -2,   4,   6],
    [10,  4, -12,  -7],
    [-3,  6,  -7, -20]
])
print_eigen_info("E3", E3)

# --- E4: Second dominant eigenvector ---
E4 = np.array([
    [10,  -3,   2,   8,  -5],
    [-3, -10,  -1,  -7,  19],
    [ 2,  -1,  -2,  13,   3],
    [ 8,  -7,  13,  -4,  18],
    [-5,  19,   3,  18,  -4]
])
print_eigen_info("E4", E4)

# --- E5: Dominant eigenvector ---
E5 = np.array([
    [ 20,  -1, -12, -12,   2],
    [ -1, -14,  18,   5,   3],
    [-12,  18,  10,  -1,  -4],
    [-12,   5,  -1,  14,  10],
    [  2,   3,  -4,  10,  18]
])
print_eigen_info("E5", E5)

# --- SVD5: Singular Values ---
print(f"\n{'='*20}\nSVD5 Analysis\n{'='*20}")
SVD5 = np.array([
    [0, -3,  -1],
    [0,  5,  -4],
    [9,  9, -10]
])
# Calculate Singular Value Decomposition
U, S, Vh = np.linalg.svd(SVD5)

print("Singular Values:")
print(S)


E2 Analysis
Eigenvalues (Sorted: 1st dominant -> least dominant):
[ 32.659386 -29.550382  12.942775  -6.051779]

Eigenvectors (Columns correspond to the sorted eigenvalues above):
[[-0.154175  0.621471  0.571663  0.513035]
 [ 0.662491 -0.137919 -0.281825  0.68019 ]
 [ 0.420989  0.742375 -0.335773 -0.398628]
 [ 0.600087 -0.20888   0.693565 -0.339459]]

E3 Analysis
Eigenvalues (Sorted: 1st dominant -> least dominant):
[-26.214271 -17.498502   8.86873   -3.155957]

Eigenvectors (Columns correspond to the sorted eigenvalues above):
[[-0.027255  0.667031  0.679652  0.303973]
 [-0.277862 -0.2621    0.57107  -0.726619]
 [ 0.500831 -0.622729  0.456116  0.39158 ]
 [ 0.819279  0.313976 -0.062536 -0.475699]]

E4 Analysis
Eigenvalues (Sorted: 1st dominant -> least dominant):
[-36.951083  21.885131  16.626307 -12.041308   0.480952]

Eigenvectors (Columns correspond to the sorted eigenvalues above):
[[ 0.115539  0.217033  0.756893 -0.138134 -0.589558]
 [-0.555601  0.169134 -0.440964 -0.462425 -0.50